# Generated by Django 5.2.8 on 2025-12-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_alter_movimientostock_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='prefijo',
            field=models.CharField(blank=True, help_text='Prefijo para códigos de artículos (ej: CH-, P-, etc)', max_length=10),
        ),
    ]
