# Generated by Django 5.2.8 on 2025-12-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_ordencompra_ordencompraitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255)),
                ('cuit', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado efectivo'), ('CTA_CTE', 'Cuenta corriente'), ('CREDITO', 'Crédito')], default='CONTADO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['razon_social'],
            },
        ),
    ]
