# Generated by Django 5.2.8 on 2025-12-05 18:53

import django.db.models.deletion
from django.db import migrations, models


def map_proveedor_ids(apps, schema_editor):
    OrdenCompra = apps.get_model("inventario", "OrdenCompra")
    Proveedor = apps.get_model("inventario", "Proveedor")

    for oc in OrdenCompra.objects.all():
        prov = Proveedor.objects.filter(razon_social__iexact=oc.proveedor).first()
        if prov:
            # Guardamos el id como texto para que la conversión a FK funcione
            oc.proveedor = str(prov.id)
            oc.save(update_fields=["proveedor"])
        else:
            # Si no encontramos proveedor, eliminamos la orden para evitar FK inválido
            oc.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_proveedor'),
    ]

    operations = [
        migrations.RunPython(map_proveedor_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra', to='inventario.proveedor'),
        ),
    ]
